### ISSUE TITLE
What about of erofsUnpackKt?

### ISSUE THREAD

**Issue by yiesko** [JamieHoSzeYui/oplus-utils#3]
In my opinion, as much as the process takes a little longer, the EROFS image can be converted to EXT4 properly and correctly.

Here the erofsUnpackKt binary: https://github.com/xiaoxindada/SGSI-build-tool/blob/12/tool_bin/erofsUnpackKt

**Comment by JamieHoSzeYui** [comment]
I'm not sure on how that works?
My method is to mount with erofs, and rebuild the image.
Both are probably just same, but that erofsunpacKt probably has a inbuilt erofs mounting logic (or binary, I'm not sure about the word to use here) but mine relies on Linux Kernel 5.4 or up (erofs is merged into linux mainline in 5.4)
